// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PimiEscoSoftWithBackEnd.Models;

namespace PimiEscoSoftWithBackEnd.Migrations
{
    [DbContext(typeof(PimiEscoSoftContext))]
    partial class PimiEscoSoftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("PimiEscoSoftWithBackEnd.Models.ClienteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Direccion");

                    b.Property<string>("Email");

                    b.Property<string>("Nombres");

                    b.Property<string>("Sexo");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PimiEscoSoftWithBackEnd.Models.FacturaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cantidad");

                    b.Property<int?>("FacturaItemId");

                    b.Property<double>("Precio");

                    b.Property<int>("ProductoId");

                    b.Property<double>("SubTotal");

                    b.HasKey("Id");

                    b.HasIndex("FacturaItemId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesFactura");
                });

            modelBuilder.Entity("PimiEscoSoftWithBackEnd.Models.FacturaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClienteId");

                    b.Property<string>("Fecha");

                    b.Property<double>("Total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("MaestroFactura");
                });

            modelBuilder.Entity("PimiEscoSoftWithBackEnd.Models.ProductoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Costo");

                    b.Property<string>("Nombre");

                    b.Property<double>("Precio");

                    b.HasKey("Id");

                    b.ToTable("ProductoItems");
                });

            modelBuilder.Entity("PimiEscoSoftWithBackEnd.Models.FacturaDetalle", b =>
                {
                    b.HasOne("PimiEscoSoftWithBackEnd.Models.FacturaItem")
                        .WithMany("FacturaDetalles")
                        .HasForeignKey("FacturaItemId");

                    b.HasOne("PimiEscoSoftWithBackEnd.Models.ProductoItem", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PimiEscoSoftWithBackEnd.Models.FacturaItem", b =>
                {
                    b.HasOne("PimiEscoSoftWithBackEnd.Models.ClienteItem", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
